In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\chakr\Downloads\SuperStoreOrders - SuperStoreOrders.csv")

In [4]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [5]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 16.5 MB

In [12]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%d/%m/%Y')

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  datetime64[us]
 2   ship_date       51290 non-null  datetime64[us]
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 15.5 MB

In [23]:
df['sales'] = pd.to_numeric(df['sales'])

In [30]:
df = df.drop(['state','region'],axis=1)

In [31]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,country,market,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Algeria,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,Australia,APAC,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Hungary,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Sweden,EU,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,Australia,APAC,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [32]:
df= df.drop(['product_id','sub_category'],axis=1)

In [34]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,country,market,category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Algeria,Africa,Office Supplies,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,Australia,APAC,Office Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Hungary,EMEA,Office Supplies,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Sweden,EU,Office Supplies,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,Australia,APAC,Furniture,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [36]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'country', 'market', 'category', 'product_name', 'sales',
       'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority',
       'year'],
      dtype='str')

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in C:\Users\chakr\miniconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in C:\Users\chakr\miniconda3\Lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\chakr\miniconda3\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\chakr\miniconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
import pandas as pd
from sqlalchemy import create_engine


DB_USER = "postgres"
DB_PASSWORD = "sql123"
DB_HOST = "localhost"
DB_PORT = "5433"
DB_NAME = "superstore_db"


engine = create_engine(f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")


table_name = "superstore_orders"

df.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",  
    index=False,          
    chunksize=5000      
)

print(f"Successfully uploaded {len(df)} rows to table '{table_name}' in PostgreSQL!")

Successfully uploaded 51290 rows to table 'superstore_orders' in PostgreSQL!